[package]
name = "lyricer"
version = "0.1.0"
authors = ["tony"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpris = "1.1"
urlencoding = "1.1"